[package]
name = "ovis-core"
version = "0.0.1"
edition = "2021"

[dependencies]
erased-serde = "0.3.27"
lazy_static = "1.4.0"
serde = { version = "1.0.166", features = ["derive"] }
serde_json = "1.0.100"
wgpu = "0.15.1"
winit = "0.28.3"
